### ISSUE TITLE
Align output format with audiosprite

### ISSUE THREAD

**Issue by eliasku** [adireddy/waudsprite#4]
Why we alter `audiosprite` output format? As result we need separated tool to generate audio sprites for `waud.js`. Maybe it could be better to just add support to `waud` for reading original `audiosprite` format file?

**Comment by adireddy** [comment]
Well, I tried to add waud support in audiosprite in 2015 but was never considered/responded for 8 months. So didn't want to rely on that just in case if I had to alter/fix anything.
https://github.com/tonistiigi/audiosprite/pull/39/files

I shifted my focus to base64 audio which it better to manage/control at runtime in my opinion. Did you consider base64 audio at all?
